"""db: schema final unificado

Revision ID: 9b11a34c37da
Revises: 
Create Date: 2025-12-03 16:15:47.411474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b11a34c37da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doadores',
    sa.Column('id_doador', sa.String(length=36), nullable=False),
    sa.Column('nome_completo', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('sexo', sa.String(length=20), nullable=True),
    sa.Column('tipo_sanguineo', sa.Enum('A_POSITIVO', 'A_NEGATIVO', 'B_POSITIVO', 'B_NEGATIVO', 'AB_POSITIVO', 'AB_NEGATIVO', 'O_POSITIVO', 'O_NEGATIVO', name='tiposanguineo'), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id_doador')
    )
    op.create_index(op.f('ix_doadores_cpf'), 'doadores', ['cpf'], unique=True)
    op.create_table('unidades_coleta',
    sa.Column('id_unidade', sa.String(length=36), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('email_unidade', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id_unidade')
    )
    op.create_index(op.f('ix_unidades_coleta_cnpj'), 'unidades_coleta', ['cnpj'], unique=True)
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.String(length=36), nullable=False),
    sa.Column('nome_completo', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('pis', sa.String(length=20), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('tipo', sa.Enum('ADMINISTRADOR', 'ATENDENTE', name='tipousuario'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('pis')
    )
    op.create_index(op.f('ix_usuarios_cpf'), 'usuarios', ['cpf'], unique=True)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('doacoes',
    sa.Column('id_doacao', sa.String(length=36), nullable=False),
    sa.Column('data_doacao', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('volume_ml', sa.Float(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('EM_ESTOQUE', 'DESPACHADA', 'DESCARTADA', name='statusdoacao'), nullable=False),
    sa.Column('tipo_sanguineo_coletado', sa.Enum('A_POSITIVO', 'A_NEGATIVO', 'B_POSITIVO', 'B_NEGATIVO', 'AB_POSITIVO', 'AB_NEGATIVO', 'O_POSITIVO', 'O_NEGATIVO', name='tiposanguineo'), nullable=False),
    sa.Column('id_doador', sa.String(length=36), nullable=False),
    sa.Column('id_registrador', sa.String(length=36), nullable=False),
    sa.Column('id_unidade', sa.String(length=36), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_doador'], ['doadores.id_doador'], ),
    sa.ForeignKeyConstraint(['id_registrador'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_unidade'], ['unidades_coleta.id_unidade'], ),
    sa.PrimaryKeyConstraint('id_doacao')
    )
    op.create_index(op.f('ix_doacoes_id_unidade'), 'doacoes', ['id_unidade'], unique=False)
    op.create_table('usuarios_unidades',
    sa.Column('id_usuario', sa.String(length=36), nullable=False),
    sa.Column('id_unidade', sa.String(length=36), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_unidade'], ['unidades_coleta.id_unidade'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_unidade')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios_unidades')
    op.drop_index(op.f('ix_doacoes_id_unidade'), table_name='doacoes')
    op.drop_table('doacoes')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_cpf'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_unidades_coleta_cnpj'), table_name='unidades_coleta')
    op.drop_table('unidades_coleta')
    op.drop_index(op.f('ix_doadores_cpf'), table_name='doadores')
    op.drop_table('doadores')
    # ### end Alembic commands ###
