-- AlterTable
ALTER TABLE `doacao` MODIFY `tipo_sanguineo_coletado` ENUM('A_POSITIVO', 'A_NEGATIVO', 'B_POSITIVO', 'B_NEGATIVO', 'AB_POSITIVO', 'AB_NEGATIVO', 'O_POSITIVO', 'O_NEGATIVO') NOT NULL;

-- AlterTable
ALTER TABLE `doador` MODIFY `tipo_sanguineo` ENUM('A_POSITIVO', 'A_NEGATIVO', 'B_POSITIVO', 'B_NEGATIVO', 'AB_POSITIVO', 'AB_NEGATIVO', 'O_POSITIVO', 'O_NEGATIVO') NULL;
